title:Fan Zhang's Homepage
page-top-title: Fan Zhang
top-section-bg-text: Be what you wanna be
home-subtitle: Fan Zhang&ensp;|&ensp;张凡
copyright-text: '&copy; Fan Zhang 2023-2025. All Rights Reserved.'
